baseURL = "https://www.bfallik.net/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Brian Fallik · Landing Page"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Brian Fallik"
  email = "bfallik@gmail.com"
  description = "Landing Page"
  bio = "10 PRINT \"Developer\"\n20 goto 10"
  avatar = "https://s.gravatar.com/avatar/52e608cf186f5df1b23575a10caec9ff?s=80"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/bfallik"
    # instagram = ""
    twitter = "https://twitter.com/bfallik"
    # ello = ""
